In [57]:
import numpy as np
import helpers
from math import exp
from random import seed
from random import random

In [58]:
# (a) Create a function which randomly initializes the weights and biases of a layer of the network.
def init_layer(a, b): # Take in the dimensions of the a x b weight matrix and b-dimensional vector.
    weight_matrix =  np.random.rand(a,b)
    bias_vector =  np.random.rand(b)
    return (weight_matrix, bias_vector)

# (b) Using the fuction created in Question 6a, create a function which randomly initializes the weights and 
#     biases of a neural network
def  init_random_network(desired_dimensions): # Take in the sizes of each layer.
    return (init_layer(desired_dimensions[0],desired_dimensions[1]), init_layer(desired_dimensions[1],desired_dimensions[2]),
           init_layer(desired_dimensions[2],desired_dimensions[3]))

initialized_network = init_random_network(dimensions)
helpers.check_my_network(dimensions, initialized_network)

dimensions = [784, 200, 100, 10]
neural_network = init_random_network(dimensions)
print(neural_network)

# (c) Utilize the function helpers.load_mnist() to obtain the data for the lab.
data = helpers.load_mnist()
train_data = helpers.load_mnist()[0]
train_labels = helpers.load_mnist()[1]
test_data = helpers.load_mnist()[2]
test_labels = helpers.load_mnist()[3]

The network is correct
((array([[0.30527234, 0.83046978, 0.39188371, ..., 0.24459611, 0.89706944,
        0.26960402],
       [0.16428639, 0.35365156, 0.66028245, ..., 0.27793602, 0.02631211,
        0.05559484],
       [0.24089729, 0.80476092, 0.61317607, ..., 0.89398241, 0.42461132,
        0.48100599],
       ...,
       [0.30530105, 0.64008925, 0.37493851, ..., 0.08897733, 0.63775409,
        0.79769009],
       [0.3487955 , 0.58065761, 0.55405086, ..., 0.74557128, 0.87559086,
        0.91753634],
       [0.85749154, 0.43592448, 0.66823806, ..., 0.81629819, 0.71488071,
        0.61691419]]), array([0.85538996, 0.26983019, 0.91505514, 0.66888247, 0.2426636 ,
       0.62138331, 0.55369804, 0.84479383, 0.54335167, 0.27660912,
       0.76743535, 0.97402266, 0.96302505, 0.47242815, 0.77791967,
       0.35905723, 0.8063137 , 0.84479322, 0.51730985, 0.31937426,
       0.11173895, 0.65915598, 0.20175644, 0.09967661, 0.78136712,
       0.35672335, 0.71289146, 0.03907672, 0.20424478, 0.83798

In [59]:
# Print the dimensions for all the data to ensure that it was obtained correctly.
print(train_data.shape)
print(train_labels.shape)
print(test_data.shape)
print(test_labels.shape)

(60000, 784)
(60000, 10)
(10000, 784)
(10000, 10)


In [60]:
# (d) Write a function which propagates a batch of data through a neural network.

# The following function will be used for the sigmoid activation function. 
def sigmoid(x):
    sig = 1/(1+np.exp(-x))
    return sig

# The following function will be used to obtain the inputs for the propagation function.
def getInputs(data,weights,bias):
    inputs = np.dot(data,weights) + bias
    return inputs

def propagate(dimensions,data):
    outputLayer = ([]) #contains output for every layer
    inputLayer= ([]) #contains input for every layer
    
    for x in range(len(neural_network)):
        layer = neural_network[x] # Access the current network
        weight_matrix = layer[0] # Access the weight matrix at the current layer.
        bias_layer = layer[1] # Access the bias layer at the current layer.
    
        if x == 0: # Uses the training data as input for the first iteration of the loop
            outputLayer = getInputs(data,weight_matrix,bias_layer)
            inputLayer = outputLayer # Output becomes input for next layer
        else:
            outputLayer = sigmoid(inputLayer)
            outputLayer = getInputs(outputLayer,weight_matrix,bias_layer)
            inputLayer = outputLayer # Output becomes input for next layer  
    outputLayer=sigmoid(inputLayer)        
    return outputLayer 

In [61]:
solution = propagate(dimensions,train_data)
print(solution)
print("Dimensions of the final network: " + str(solution.shape))

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
Dimensions of the final network: (60000, 10)
